baseURL = 'https://herdeirosdegaia.org.br/'
languageCode = 'pt'
title = 'GE 146 PR - Herdeiros de Gaia'
theme = 'ananke/'

DefaultContentLanguage = "pt"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set     to a higher number
googleAnalytics = ""
enableRobotsTXT = true
 
[languages]
  [languages.pt]
    title = "GE 146 PR - Herdeiros de Gaia"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.en]
    title = "GE 146 PR - Herdeiros de Gaia"
    weight = 2
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
   changefreq = "monthly"
   priority = 0.5
   filename = "sitemap.xml"
  
[params]
   text_color = ""
   author = "Mateus Bernardo"
   #body_classes = "sans-serif bg-dark-green"
   favicon = ""
   site_logo = ""
   description = "The last theme you'll ever need. Maybe."
   # choose a background color from any on this page: https://tachyons.io    /docs/themes/skins/ and preface it with "bg-"
   background_color_class = "bg-dark-green"
   recent_posts_number = 3
   show_reading_time = "true"
   date_format = "2. January 2006"

  
[[params.ananke_socials]]
   name = "instagram"
   url = "https://www.instagram.com/ge.morgenau/"
[[params.ananke_socials]]
   name = "facebook"
   url = "https://www.facebook.com/ge.morgenau/"
